name: my_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  auto_route: ^9.3.0+1
  rive: ^0.13.12
  flutter_svg: ^2.0.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  auto_route_generator: ^9.3.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
